# Generated by Django 5.1.5 on 2025-01-23 10:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dialogue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(choices=[('course_info', 'Информация о курсах'), ('pricing', 'Стоимость обучения'), ('schedule', 'Расписание занятий'), ('trial', 'Пробное занятие'), ('age', 'Возрастные группы'), ('technical', 'Технические вопросы'), ('other', 'Другое')], max_length=50, verbose_name='Тема')),
                ('requires_crm', models.BooleanField(default=False, verbose_name='Требуется доступ к CRM')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
            ],
            options={
                'verbose_name': 'Диалог',
                'verbose_name_plural': 'Диалоги',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(choices=[('user', 'Клиент'), ('assistant', 'Менеджер')], max_length=20, verbose_name='Автор')),
                ('text', models.TextField(verbose_name='Текст сообщения')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('dialogue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='dialogues_app.dialogue')),
            ],
            options={
                'verbose_name': 'Сообщение',
                'verbose_name_plural': 'Сообщения',
                'ordering': ['created_at'],
            },
        ),
    ]
